name = "learning-notes-web"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "learning-notes-db"
database_id = "db95fb53-6dcb-4687-9469-7fc15036ff01"
